apiVersion: apps/v1
kind: Deployment
metadata:
  name: impression-app
  labels:
    app: impression-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: impression-app
  template:
    metadata:
      labels:
        app: impression-app
    spec:
      containers:
        - name: impression-app
          image: walidbenhamid1/impression:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://yamanote.proxy.rlwy.net:45062/railway"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "LPxFTGmgbOrVyxhXjYDckJzAKFQPqDnJ"
            - name: SERVER_PORT
              value: "8083"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 5
