apiVersion: v1
kind: Service
metadata:
  name: impression-service
  labels:
    app: impression-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-external-ip: "192.168.49.2"
    service.beta.kubernetes.io/aws-load-balancer-internal-ip: "10.108.90.125"
    service.beta.kubernetes.io/aws-load-balancer-ip: "10.108.90.125"
spec:
  selector:
    app: impression-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30080
  type: LoadBalancer
  externalIPs:
    - "192.168.49.2"
    - "192.168.1.100"
