apiVersion: v1
kind: Service
metadata:
  name: impression-service
  labels:
    app: impression-app
spec:
  selector:
    app: impression-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30080
  type: NodePort
